"""Qt 绑定的统一导入出口。

职责边界：
- 做：集中转出项目用到的全部 Qt 符号，作为唯一的 Qt 绑定入口。
- 不做：不封装任何业务逻辑；不做控件二次封装。

依赖：无（只依赖 PyQt6 本身）；被依赖：几乎全部 GUI 与含信号的 core 模块。

All GUI / signal code imports Qt classes from this module instead of directly
from PyQt6. This keeps the project *forward-looking*: switching to PySide6
(LGPL — better for proprietary distribution, see README "授权 License") becomes
a single-file change here, rather than touching every widget.

We standardize on **PyQt6** (best Python 3.13 support, actively maintained).
"""

from PyQt6.QtCore import (
    Q_ARG,
    QAbstractItemModel,
    QCoreApplication,
    QDir,
    QEvent,
    QFileInfo,
    QItemSelectionModel,
    QLocale,
    QMetaObject,
    QModelIndex,
    QObject,
    QPoint,
    QRect,
    QRunnable,
    QSettings,
    QSize,
    QStandardPaths,
    Qt,
    QThread,
    QThreadPool,
    QTimer,
    QTranslator,
    QUrl,
)
from PyQt6.QtCore import (
    pyqtSignal as Signal,
)
from PyQt6.QtCore import (
    pyqtSlot as Slot,
)
from PyQt6.QtGui import (
    QAction,
    QBrush,
    QCloseEvent,
    QColor,
    QDesktopServices,
    QDragEnterEvent,
    QDropEvent,
    QFont,
    QIcon,
    QKeySequence,
    QPainter,
    QPen,
    QPixmap,
    QResizeEvent,
    QWheelEvent,
)
from PyQt6.QtWidgets import (
    QAbstractItemView,
    QApplication,
    QCheckBox,
    QComboBox,
    QFileDialog,
    QFormLayout,
    QFrame,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QMainWindow,
    QMenu,
    QMessageBox,
    QProgressBar,
    QPushButton,
    QRadioButton,
    QScrollArea,
    QSizePolicy,
    QSlider,
    QSpacerItem,
    QStackedWidget,
    QTableWidget,
    QTabWidget,
    QToolButton,
    QVBoxLayout,
    QWidget,
)

__all__ = [
    "QObject",
    "QThread",
    "QRunnable",
    "QThreadPool",
    "QTimer",
    "QSize",
    "QUrl",
    "QRect",
    "QPoint",
    "QEvent",
    "QMetaObject",
    "Q_ARG",
    "Qt",
    "QStandardPaths",
    "QDir",
    "QFileInfo",
    "QSettings",
    "QTranslator",
    "QLocale",
    "QCoreApplication",
    "QAbstractItemModel",
    "QModelIndex",
    "QItemSelectionModel",
    "Signal",
    "Slot",
    "QIcon",
    "QFont",
    "QColor",
    "QAction",
    "QDragEnterEvent",
    "QDropEvent",
    "QDesktopServices",
    "QPixmap",
    "QPainter",
    "QPen",
    "QBrush",
    "QKeySequence",
    "QCloseEvent",
    "QResizeEvent",
    "QWheelEvent",
    "QApplication",
    "QWidget",
    "QMainWindow",
    "QFileDialog",
    "QMessageBox",
    "QListWidget",
    "QListWidgetItem",
    "QHBoxLayout",
    "QVBoxLayout",
    "QGridLayout",
    "QFrame",
    "QLabel",
    "QProgressBar",
    "QComboBox",
    "QLineEdit",
    "QPushButton",
    "QAbstractItemView",
    "QSizePolicy",
    "QSpacerItem",
    "QStackedWidget",
    "QScrollArea",
    "QGroupBox",
    "QCheckBox",
    "QRadioButton",
    "QSlider",
    "QTabWidget",
    "QTableWidget",
    "QHeaderView",
    "QFormLayout",
    "QToolButton",
    "QMenu",
]
